/*
 * Glutz App API
 *
 * API to access and configure the Glutz
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiservices

import (
	"context"
	"errors"
	"net/http"
	"glutz/apiserver"
)

// DevicesApiService is a service that implements the logic for the DevicesApiServicer
// This service should implement the business logic for every endpoint for the DevicesApi API.
// Include any external packages or services that will be required by this service.
type DevicesApiService struct {
}

// NewDevicesApiService creates a default api service
func NewDevicesApiService() apiserver.DevicesApiServicer {
	return &DevicesApiService{}
}

// GetDevices - List all devices mapped to eliona assets
func (s *DevicesApiService) GetDevices(ctx context.Context, configId int64) (apiserver.ImplResponse, error) {
	// TODO - update GetDevices with the required logic for this service method.
	// Add api_devices_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Device{}) or use other options such as http.Ok ...
	//return Response(200, []Device{}), nil

	return apiserver.Response(http.StatusNotImplemented, nil), errors.New("GetDevices method not implemented")
}
